[package]
name = "match"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = 2
opt-level = 0

[dependencies]
bincode = "1.3.3"
tonic = "0.8.1"
prost = "0.11.0"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread", "signal"] }
once_cell = "1.8"
uuid = { version = "1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
sqlx = { version = "0.8.1", features = ["mysql", "time", "runtime-tokio" ] }
serde = "1.0.92"
serde_json = "1.0"
serde_derive = "1.0.92"
log = "0.4.0"
env_logger = "0.10"
toml = "0.5.1"
lazy_static = "1.4"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.75"
num = "0.4"
secp256k1 = "0.29"
hex = "0.4.3"
digest = "0.10"  
sha3 = { version = "0.10"}
prometheus = "0.13"
hyper = { version = "^0.14", features = ["server", "http1", "tcp"] }

bytes = { version = "1", optional = true }
fxhash = "0.2.1"
fail = { version = "0.4", optional = true }
getset = "0.1.1"
protobuf = "2"
thiserror = "1.0"
rand = "0.8"
slog = "2.2"
slog-envlogger = { version = "2.1.0", optional = true }
slog-stdlog = { version = "4", optional = true }
slog-term = { version = "2.4.0", optional = true }
regex = "1.11.1"
slog-async = "2.8.0"
tempfile = "3.8.1"

raft = { git = "https://github.com/zxz2801/raft-rs.git", branch = "feat/raft_match" }
raft-proto = { git = "https://github.com/zxz2801/raft-rs.git", branch = "feat/raft_match" }

rust_decimal = { version = "1.30", features = ["serde-str"] }
rust_decimal_macros = "1.30"
tokio-stream = "0.1.17"

[build-dependencies]
tonic-build = "0.8.0"

[features]
default = ["slog-term"]
