id = 1
start_with_leader = true
addr = "0.0.0.0:4001"
metrics_addr = "0.0.0.0:4011"
base_path = "./data1"
[[node_list]]
id = 1
addr = "grpc://127.0.0.1:4001"

[[node_list]]
id = 2
addr = "grpc://127.0.0.1:4002"

[[node_list]]
id = 3
addr = "grpc://127.0.0.1:4003"
