id = 3
start_with_leader = false
addr = "0.0.0.0:4003"
metrics_addr = "0.0.0.0:4013"
base_path = "./data3"
[[node_list]]
id = 1
addr = "grpc://127.0.0.1:4001"

[[node_list]]
id = 2
addr = "grpc://127.0.0.1:4002"

[[node_list]]
id = 3
addr = "grpc://127.0.0.1:4003"
